### ISSUE TITLE
Document possible use on CI environments (non-interactive shells)

### ISSUE THREAD

**Issue by ssbarnea** [hyperupcall/autoenv#164]
I am wondering if autoenv could not be used in complex CI environments where we have multiple steps and where we need to save/restore status between different steps.

We are currently doing appending variables inside some `env_jenkins.properties` files and on some some steps (builders) and on others we do `source env_jenkins.properties` in order to load them.

If `autoenv` would work also for CI scripts it would be wonderful. Even if it doesn't I think this is should be documented as well.

**Comment by hyperupcall** [comment]
Hi! :wave: 

Hmm, I don't see a reason that `autoenv` wouldn't work in CI. I think the main thing is that I don't see CI being a super strong use case for `autoenv`, which is why it isn't in any documentation. Definitely feel free to use it for CI - I just don't see a huge enough reason to put it in the docs
