### ISSUE TITLE
Uninstall autoenv - Mac OS Ventura 13.0

### ISSUE THREAD

**Issue by selimharfouche** [hyperupcall/autoenv#216]
Hello, I can't seem to uninstall it.

### Installation

First, I followed the instructions and installed via brew
`$ brew install autoenv`
`$ echo "source $(brew --prefix autoenv)/activate.sh" >> ~/.bash_profile`
`source ~/.bash_profile`

Since it did not work, I used this code that was posted in an issue
`echo "source $(brew --prefix autoenv)/activate.sh" >> ~/.zshrc`
`source ~/.zshrc`

### Uninstallation trials

- I deleted the added line in both ~/.bash_profile & ~/.zshrc

`brew uninstall autoenv`

- I also ran cd unset.

When I cd into the directory, it stills activate.

**Comment by hyperupcall** [comment]
Gosh I should really update the instructions for both Bash and Zsh since the former is now the default on macOS - I don't use macOS so that's the reason why this slipped for so long...

About your question @selimharfouche , your issue seems to be that `unset cd` isn't doing what you think it's doing

In Bash `unset cd` tries to find a variable named `cd` - if that variable name is not found, looks for a function named `cd` and removes it if it can be found

But in Zsh, `unset cd` stops if it can't find a variable named `cd`. You have to do either `unset -f cd` or `unfunction cd` so the actual function is actually unset

**Comment by hyperupcall** [comment]
I'll have to update the documentation so this is more clear - thanks for bringing this up

If that didn't work, please let me know, and I'll investigate further :)
