### ISSUE TITLE
Autoenv keep asking for permission

### ISSUE THREAD

**Issue by zhouhao27** [hyperupcall/autoenv#224]
**Platform**
 - Operating system and version? **macOS 13 ventura**
 - Shell and version? **zsh**
 - autoenv installation method **brew**
 - autoenv version **Latest version**, don't know how to get the version number
 
**Describe the bug**

It shows the following message every time when I enter the directory.

> autoenv: This is the first time you are about to source /Volumes/T7/Users/....../.env:
autoenv:
autoenv:   --- (begin contents) ---------------------------------------
autoenv:     NAME=dev^M$
autoenv:     .....
autoenv:     .....
autoenv:     ^M$
autoenv:
autoenv:   --- (end contents) -----------------------------------------
autoenv:
autoenv: Are you sure you want to allow this? (y/N) 

**Expected behavior**

Should only show once after I answered **N**. Am I right?

**Additional context**

My `.env` file in this directory is for other purpose.

**Comment by hyperupcall** [comment]
Hey! The behavior you expect makes sense, but unfortunately it's not implemented that way.

I merged #226 to fix this. When prompted, you can reply with `D` or `d` which I suppose could stand for _deny always_.

Since you're using Homebrew, you can easily use this new feature. I believe the commands are:

```sh
brew uninstall bats-core
brew install bats-core --head
```

There are [quite a few changes](https://github.com/hyperupcall/autoenv/compare/v0.3.0...master) since v0.3.0 that are also implemented on HEAD, so please let me know things work as you expected. I tested locally and added tests so things work on my machine :smiley:

**Comment by zhouhao27** [comment]
@hyperupcall Got the following error:

> Error: No head is defined for bats-core

**Comment by hyperupcall** [comment]
@zhouhao27 Ah goodness I'm sorry - for some reason I wrote the wrong package. I updated my previous comment so it installs the `autoenv` package.

**Comment by hyperupcall** [comment]
epic!
