### ISSUE TITLE
autoenv running on all directories in parent

### ISSUE THREAD

**Issue by ashtonian** [hyperupcall/autoenv#228]
**Platform**
Installed this morning via `brew install autoenv --head`
 - Operating system and version? Ventura 13.4 on M2
 - Shell and version? ZSH + OMZ + Plugins
 - my [.zshrc](https://github.com/Ashtonian/dotfiles/blob/master/.zshrc)
 
**Describe the bug**

Whenever I cd or jump into a directory autoenv runs on every parent directory. I'm assuming this is a conflict with another plugin but I'm not sure which one - maybe [auto-color-ls](https://github.com/gretzky/auto-color-ls). Any ideas? 

```sh
cd Projects
 projects/                                  ✔  11:53:09   ▓▒░

       charts/
       lab/
       notes/
       patchy/
       .DS_Store
       rank-amateur-cowsay-master.zip
shasum:        var : No such file or directory
autoenv_source:.:6: no such file or directory:        var
shasum:        tmp : No such file or directory
autoenv_source:.:6: no such file or directory:        tmp
shasum:        home : No such file or directory
autoenv_source:.:6: no such file or directory:        home
shasum:        etc : No such file or directory
autoenv_source:.:6: no such file or directory:        etc
shasum:        .file : No such file or directory
autoenv_source:.:6: no such file or directory:        .file
shasum:        .VolumeIcon.icns : No such file or directory
autoenv_source:.:6: no such file or directory:        .VolumeIcon.icns
shasum:        usr/: No such file or directory
autoenv_source:.:6: no such file or directory:        usr/
shasum:        sbin/: No such file or directory
autoenv_source:.:6: no such file or dir
```
**Expected behavior**

Only to run on current directory.

**Comment by hyperupcall** [comment]
Hey,

I haven't used `auto-color-ls` but the `autoenv` source code does not use `ls` (and neither `dir` nor `vdir`), so I'm not sure what could be conflicting. The most troublesome builtins and all external commands are ran either `builtin` and `command` respectively, so that should be preventing any issues from potentially conflicting plugins;

I'll close this issue since it doesn't seem to be an issue with `autoenv` - if you've found the troublesome plugin, I'd be interested in knowing which one it is;
